apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-producer
  template:
    metadata:
      labels:
        app: redis-producer
    spec:
      containers:
      - name: redis-producer
        image: redis-producer:v1

