apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-producer
  namespace: my-kube-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-producer
  template:
    metadata:
      labels:
        app: redis-producer
    spec:
      containers:
        - name: redis-producer
          image: patterson2014/redis-producer:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: producer-config

