apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-kube-namespace
spec:
  selector:
    app: producer
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082  # ✅ Changed to avoid conflict

